#!/usr/bin/env bash
# Package the API as a Lambda-ready folder at dist/apps/api:
#   serverless.js      — the webpacked Lambda entry (serverless.ts)
#   package.json       — generated by webpack, exact runtime dep versions
#   node_modules       — production-only install resolved from that manifest
#
# No @nx/js:prune-lockfile: the executor requires apps/api/package.json, which
# this workspace deliberately doesn't have (deps are hoisted at the root, see
# CLAUDE.md). The webpack-generated manifest is the accurate dependency list
# anyway — it is derived from the bundle's actual imports.
#
# The Pulumi program zips these into the Lambda code archive (SPEC.md §323 —
# Nest ships as a Lambda zip). Run before any `pulumi preview/up`.
set -euo pipefail
cd "$(dirname "$0")/.."

# The lambda configuration is a first-class build configuration (project.json):
# its env (LAMBDA_BUILD=1) is part of the nx cache key, so a cached main.js
# build can never be served up as the Lambda artifact. Exporting the env var
# at the shell would bypass that — the cache would reuse the wrong output.
npx nx run api:build:lambda
(
  cd dist/apps/api
  rm -rf node_modules package-lock.json
  npm install --omit=dev
)

echo "Lambda package ready at dist/apps/api"
